### PR TITLE
Update collection-hooks version

### PR DESCRIPTION
**Pull request by Floriferous**

### CODE REVIEW

**Comment by pmogollons** [comment]
Looks like this will also need's an update on herteby:denormalize as that package also requires v0.8.4

**Comment by Floriferous** [comment]
@theodorDiaconu Bump!

**Comment by theodorDiaconu** [comment]
@Floriferous as you can see the tests are failing due to interdependency hell:
```

   While selecting package versions:
   error: Conflict: Constraint matb33:collection-hooks@0.8.4 is not satisfied
   by matb33:collection-hooks 1.0.1.
   Constraints on package "matb33:collection-hooks":
   * matb33:collection-hooks@1.0.1 <- local-test:cultofcoders:grapher 1.3.19
   * matb33:collection-hooks@1.0.1 <- cultofcoders:grapher 1.3.19 <-
   local-test:cultofcoders:grapher 1.3.19
   * matb33:collection-hooks@0.8.4 <- herteby:denormalize 0.6.5 <-
   cultofcoders:grapher 1.3.19 <- local-test:cultofcoders:grapher 1.3.19
   * matb33:collection-hooks@0.8.4 <- herteby:denormalize 0.6.5 <-
   local-test:cultofcoders:grapher 1.3.19
   
```

**Comment by StorytellerCZ** [comment]
Included in version 1.3.20

**Pull request closed without merging**
