### PR TITLE
Reducers

### PR DESCRIPTION
**Pull request by bhunjadi**
This PR should resolve the issue #254.

## Description
As discussed in the issue, I rearranged prepareForDelivery function so that `storeOneResults` is called before `applyReducers`.
Consequently, I made changes to the pipeline functions between new and old `storeOneResults` call location.

## Warning
These are breaking changes for everybody who used reducer dependent on the One link. The link value will not be an array anymore, but an object (or undefined).

### CODE REVIEW

**Comment by theodorDiaconu** [comment]
@bhunjadi great PR!. I am aware that we introduce a breaking change... wonder how we can mitigate this.

Also, what if we do: `removeLinkStorages()`  like this:
```js
removeLinkStorages()
    storeOneResults(node, node.results);
    applyReducers(node, params);
    cleanReducerLeftovers(node);
```

This would make getArrayResults obsolete. What do you think @bhunjadi  ?

**Comment by bhunjadi** [comment]
Don't know what would be the best way to mitigate this breaking change, but perhaps we could agree that it comes from a bug fix so it is not that bad.

As for `removeLinkStorages()`, I've tried to put it before `storeOneResults()` but then *Hypernova - $meta filters* tests have failed. I think it is because `assembleMetadata()` uses link storages.
It seems that `removeLinkStorages()` is in the right place at the moment.

Anyway, it looks like are stuck with `getArrayResults()` because functions in the pipeline assume array results, so everything after `storeOneResults()` should have it.

Or am I missing something @theodorDiaconu ?

**Comment by theodorDiaconu** [comment]
@bhunjadi you aren't missing anything, you're right. Grapher is a complex monster and it's good to have tests to remind us of why certain decisions have been made this way. 

I think you're right this is kind-of a bug-fix. But somehow people need to be aware of this change, we'll need to write it in  MIGRATIONS.md

**Comment by bhunjadi** [comment]
Great!
I'll update MIGRATION.md with an example today or tomorrow.

**Pull request merged**
