### PR TITLE
Grapher 1.4

### PR DESCRIPTION
**Pull request by StorytellerCZ**
Includes #462 and new Travis CI test with Meteor 2.6.

Currently the test fails on 4 things. Not sure which ones as locally I did not have the problem.

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
@donstephan looks like tests for 2.7.3 are fine, but tests for earlier versions are failing. I'll try to do quickly look into doing some backward compatibility.

**Comment by vparpoil** [comment]
@StorytellerCZ  I think backward compatibility broke due to mongo driver version, and I believe [this commit was enabling backward compatibility](https://github.com/cult-of-coders/grapher/pull/467/files#diff-94d86fa6734d96e962688bebb6f66208b2e68c963d654ff15cd67b7bdd1a130dR8) (I haven't tested though)
Thank you for pushing this forward !

**Comment by donstephan** [comment]
I think the tests are failing due to in 2.5+ the internal collection document map is an actual `Map` and not an object.

```
// swap this over to an object
// since in 2.5+ an actual Map is used
const docMap = Object.fromEntries(Posts._collection._docs._map);
```

I should have checked if it's a map i.e.
```
const docMap = Posts._collection._docs._map instanceof Map ? Object.fromEntries(Posts._collection._docs._map) : Posts._collection._docs._map;
```

I'll fix this up tonight and make sure tests pass for all the versions that they run against.

**Comment by StorytellerCZ** [comment]
@donstephan thanks a lot!
If needed we might want to bump a minimum Meteor version, though that would be something best reserved for a major version update.

**Comment by StorytellerCZ** [comment]
@donstephan thank you very much for your contribution!

Anything urgent that should be added into this release?

**Comment by donstephan** [comment]
I'm good on my end. I think that covers everything for Meteor 2.6+ which was the goal. Thanks!

**Comment by StorytellerCZ** [comment]
Alright! Moving ahead with the release.

**Comment by StorytellerCZ** [comment]
Released!

**Pull request merged**
