### PR TITLE
[WIP] beginning shifting to simpl-schema

### PR DESCRIPTION
**Pull request by theodorDiaconu**

### CODE REVIEW

**Comment by macsj200** [comment]
I'm very motivated to get this PR merged in ASAP, do you have any ideas about what needs fixing? Also, maybe we should have a fallback mechanism so people still using SimpleSchema can use the package.

**Comment by macsj200** [comment]
Ok, I opened [an issue on simpl-schema](https://github.com/aldeed/node-simple-schema/issues/116), hopefully we can get this resolved soon (no pun intended).

**Comment by macsj200** [comment]
I made a [PR](https://github.com/cult-of-coders/grapher/pull/137) for this branch to fix the `blackbox` issues, but now I'm getting the error `Publication is required`. I believe this is coming from the fixtures, not sure exactly where yet.

**Comment by macsj200** [comment]
Check this out https://github.com/aldeed/meteor-collection2/issues/364

**Comment by theodorDiaconu** [comment]
@macsj200 fixed and published to 1.1.8 :) we have no compatibility.

**Pull request closed without merging**
