### PR TITLE
Links on nested fields

### PR DESCRIPTION
**Pull request by bhunjadi**
This PR enables links on nested fields.

While I 100% agree with you that we should keep links in top level fields there are some situations where this is not possible. Example is when using some other packages, such as [Meteor-Files](https://github.com/VeliovGroup/Meteor-Files).

They recommend using `meta` object to store your metadata, eg
```
meta: {
  projectId: '...',
}
```

With this PR link on meta.projectId is possible.

### CODE REVIEW

**Comment by theodorDiaconu** [comment]
Wow. I will take a closer look here. Because I remember there was a good reason performance wise also why I chose not to do this.

**Comment by theodorDiaconu** [comment]
Only one concern. Performance. https://github.com/theodorDiaconu/grapher-performance can you check it with or without these changes see what impact is has ? (I don't care about nested fields storage performance)

**Comment by bhunjadi** [comment]
Ok, I'll do the tests and send the results.

So if I understand you correctly, you are concerned about CPU performance, meaning overhead of these changes. 
Queries for links on top level fields remain the same. Therefore DB performance should be the same.

**Comment by theodorDiaconu** [comment]
Yes, indeed.

**Comment by bhunjadi** [comment]
I've done some tests and there is performance impact to some extent, but can't say if it is significant.
How I've tested:
- using local database because we want to see CPU diff
- using [Query 3](https://github.com/theodorDiaconu/grapher-performance/blob/master/TEST_RESULTS.md) from grapher-performance
- tracking time for whole query, prepareForDelivery and removeLinkStorages execution times

### Master
query 3 - master

### Nested Fields
query 3 - nested

### Results
On average, nested fields are slower by a few milliseconds.
However, I do have an idea about some optimizations but first have to come up with better performance calculations so that it will be easier to compare between versions.

**Comment by theodorDiaconu** [comment]
Calculation should be an average of 500 tries. This is how I usually did it.

**Pull request merged**
