### PR TITLE
Apply collection transforms after aggregations

### LINKED ISSUE #420: Aggregated results don't apply collection's transform
Grapher relies on mongo aggregations to perform queries sometimes. Aggregations don't apply a collection's transform to them, leading to very inconsistent results.

On the server for example, depending on if you fetch 2 linked documents one way or the other (virtual link, or not), the transform will not be applied.

This is what I meant in #186.

### PR DESCRIPTION
**Pull request by Floriferous**
Closes #420 

This applies a collection transform right after aggregations

### CODE REVIEW

**Comment by bhunjadi** [comment]
I've taken similar approach with #400 where `aggregate` for virtual links is replaced with `find`. There's no need to handle these from within grapher in that case.

There's also discussion in #387 about aggregate vs find.

**Comment by Floriferous** [comment]
Yeah, that'd be great, this PR is a bit hacky anyways. Let's hope we can get these merged.

**Comment by Floriferous** [comment]
Maybe you can port over my tests however.

**Comment by bhunjadi** [comment]
Yes, I did not test the effects of transform there. I'll update the PR with your tests.

**Pull request closed without merging**
