### PR TITLE
updated package.js, updated packages, fixed broken tests

### PR DESCRIPTION
**Pull request by donstephan**
- updated denormalize package
- note that sift was quite a few versions back
- all tests are passing

### CODE REVIEW

**Comment by theodorDiaconu** [comment]
looks good, the previous problems I had were related to `meteor publish`. Can you try a publication of  your fork to see it works ok, other than that thank you.

**Comment by donstephan** [comment]
It gets through all the pre-publish functions well (which I believe makes it past the interdependency checks). The `versionsfrom` should handle the version constraints issue that was being had since that now syncs with `matb33:collection-hooks`. `herteby:denormalize@0.6.6` has been updated to use the latest version of that package as well. Happy to actually publish a package if you think it's necessary though.

**Comment by paulincai** [comment]
Hi @theodorDiaconu. Is this ok to get a merge?

**Comment by donstephan** [comment]
Following up on this. Need anything else on my end?

**Comment by StorytellerCZ** [comment]
@donstephan yes, thank you! I will test now and release if test pass.

**Review by StorytellerCZ — APPROVED** [review]

**Comment by donstephan** [comment]
thanks!

**Comment by StorytellerCZ** [comment]
@donstephan had to revert the use of `Object.fromEntries` in tests. Can you please take a look on that?

**Comment by StorytellerCZ** [comment]
See #461

**Comment by donstephan** [comment]
Looks good, not sure why I had to change that to be `Object.fromEntries` for tests to pass locally. I suspect I was using a different driver. Thanks for setting up Jenkins again. I'll test the release in a few hours here.

**Comment by StorytellerCZ** [comment]
Great, let me know if everything is working fine. I haven't had an opportunity to test things beyond automated tests, so any feedback is welcomed.

**Pull request merged**
