### PR TITLE
Remove practicalmeteor:chai

### PR DESCRIPTION
**Pull request by bhunjadi**

### CODE REVIEW

**Comment by bhunjadi** [comment]
@theodorDiaconu 

It looks like only meteortesting:mocha works. Both decaffed:mocha and cultofcoders:mocha cannot find tests.

**Comment by theodorDiaconu** [comment]
@bhunjadi this is so strange. I'll also have a look on this and keep you in the loop.

**Comment by bhunjadi** [comment]
Any idea how we should resolve
```
import chai from 'chai';
global.assert = chai.assert;
```

One solution is to import in every test file. Are there any better solutions?

**Comment by theodorDiaconu** [comment]
I think it's more than fine to import them in every test file. That's how it should've been in the beginning

**Pull request merged**
