### PR TITLE
Prepare changelog for 1.3.20 release

### PR DESCRIPTION
**Pull request by StorytellerCZ**

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
@theodorDiaconu do we need to re-setup Travis?

**Comment by StorytellerCZ** [comment]
Tests now running and passing on Travis:
https://app.travis-ci.com/github/StorytellerCZ/grapher/builds/246871774

I have published cultofcoders:grapher@1.3.20-beta.0 so that it can be tested by people, before release. Please commet here for any issues encountered.

**Comment by donstephan** [comment]
Something is up with 2.6+ and the aggregate function. The comment [here](https://github.com/cult-of-coders/grapher/pull/458#issuecomment-1038431738) on #458 fixes this but the [aggregate.js](https://github.com/cult-of-coders/grapher/blob/master/lib/aggregate.js) file needs some love to make it backwards compatible. I'll hopefully get an update for this by tomorrow evening. Can an additional test on Travis be run with a release of 2.6+? We're going across quite a few versions here and it would be nice to have that coverage.

**Comment by StorytellerCZ** [comment]
Meteor 2.6 is a big MongoDB upgrade when it comes to internal. Let's focus on 2.3 in this patch on 2.6 on the next one, to make updates easier for people.

**Comment by StorytellerCZ** [comment]
Since there have been no complains, I'm merging this and releasing 1.3.20.
@donstephan let's take a look on getting everything sorted for another patch/feature release to get Meteor 2.6 support.

**Comment by donstephan** [comment]
Awesome thanks! Makes sense for this release. I'll get everything organized for 2.6 in a separate PR.

**Comment by StorytellerCZ** [comment]
@donstephan thanks a lot! I'm sorry that I can't help more at this time, but hopefully in few months.

**Comment by StorytellerCZ** [comment]
In the meantime I'll try to get Travis CI up and running on this repo.

**Comment by donstephan** [comment]
You've helped a ton! I'm happy to manage this. Do you want to continue with Travis? I can migrate it over to Github actions if that's easier.

**Comment by StorytellerCZ** [comment]
If you want to do GitHub actions I'm fine with that, let's have that as a separate PR. I can try to help with that as well.

**Pull request merged**
