### PR TITLE
update to aldeed:collectdion2-core and aldeed:node-simple-schema

### PR DESCRIPTION
**Pull request by jensvrai**
Hi Theodore,

I updated the aldeed:collection2 package to use the aldeed:collection2-core package
and used the npm package aldeed:node-simple-schema

### CODE REVIEW

**Comment by theodorDiaconu** [comment]
Nice your PR looks good. But I will give it a better look this week, and will merge it. Thanks

**Comment by theodorDiaconu** [comment]
@jensvrai why are the tests failing, any idea ?

**Comment by jbbr** [comment]
@jensvrai the "named classes" bugs has been fixed since Meteor `1.4.2.7` - https://github.com/meteor/meteor/issues/8312
So the commit 687fa2fbd766a1d9504fca069096184fc71ea759 could be reverted or is now only a code-style choice.

**Comment by theodorDiaconu** [comment]
@jensvrai the simpl-schema is highly unreliable at this stage. I tried, wasted abotu 1h to make it work it has bugs with { type: [String] }, collection2 doesn't depend on it directly so tests fail bc of that. Pls re-open this bc in future we will surely shift.

**Comment by jensvrai** [comment]
@theodorDiaconu ok thx, I'll keep working on it.

**Comment by Twisterking** [comment]
Any chance for a fix?! I think this constraint prevents many users from using grapher as pretty much everyone is using the newer `aldeed:collection2-core` and the npm `simpl-schema`.

**Comment by jensvrai** [comment]
@Twisterking You can keep using my fork, but I am not working on it anymore and no longer using grapher for new projects

**Comment by theodorDiaconu** [comment]
@jensvrai why aren't you using grapher for new projects ?
@Twisterking this will be fixed this month

**Pull request merged**
