### PR TITLE
fix shift to simpl schema

### PR DESCRIPTION
**Pull request by macsj200**
`simpl-schema` [doesn't behave as expected](https://github.com/aldeed/node-simple-schema/issues/39) with `blackbox` if using `SimpleSchema.oneOf`.

### CODE REVIEW

**Comment by macsj200** [comment]
(still needs some work)

**Comment by theodorDiaconu** [comment]
nice @macsj200 thank you, this month I will invest in grapher at least 20 hours and will fix them.

**Comment by macsj200** [comment]
Awesome, let me know if I can help out anywhere. I have a flexible schedule and could screen share with you if you'd like.

**Comment by theodorDiaconu** [comment]
@macsj200  add me on skype theodor.dt maybe we can work together on this on monday to put an end to it. Cheers!

**Comment by macsj200** [comment]
Hi Theodor, I think I sent you a contact request on skype, but I'm not sure if you got it. My handle is `macsj200`, lmk if you are still down to work today. I'm not sure where you are located so IDK how timezones work out, I'm located in LA but I am down to collab whenever works for you.

**Pull request closed without merging**
