### PR TITLE
Fix failed queries in Meteor 2.6 due to custom aggregate function

### PR DESCRIPTION
**Pull request by gwhobbs**
Was crashing in Meteor 2.6 (queries failed to execute).

As discussed in https://github.com/cult-of-coders/grapher/pull/458#issuecomment-1038431738

### CODE REVIEW

**Comment by jthomaschewski** [comment]
I can confirm that this indeed fixes grapher in Meteor 2.6. Thanks

**Comment by StorytellerCZ** [comment]
Ran the tests on 2.6.1, all green. I'm not sure if this should be a patch or feature release.

**Comment by paulincai** [comment]
I'd consider it a release. This is the official new version as a community package. Since the previous owner will probably not push any further updates I wonder if we can fork and start under a new owner and advise everyone to migrate to the new packages. This is an opportunity to also remove the branding which is not Meteor specific or related.

**Comment by StorytellerCZ** [comment]
Closing this as it was integrated into #466. MCP now has publishing rights to Grapher, so I will try to get a release soon as the tests pass.

**Pull request closed without merging**
